image: nvcr.io/nvidia/pytorch:21.10-py3
port: 8000
command:
  - /bin/sh
  - '-c'
  - |
    cd /opt/repos/repo
    pip install -r requirements.txt
    python app.py
repositories:
  dataset: dsh6ec65wbbg9kx
  mountPath: /opt/repos
  repositories:
    - url: https://github.com/milo157/Deployments-Arize-Tutorial
      name: repo
      ref: main
resources:
  replicas: 1
  instanceType: C5
